### ISSUE TITLE
adventuremap is broken in release-0.1.38

### ISSUE THREAD

**Issue by jishnu7** [play-co/adventuremap#8]
```
Uncaught TypeError: Cannot read property 'length' of undefined 
```

on line number https://github.com/gameclosure/adventuremap/blob/master/views/AdventureMapView.js#L114

Seems like _touchIDs, used for pinch to zoom is removed from ScrollView

**Comment by bubbleboy14** [comment]
Nice catch! Pull latest master for the fix. Thanks for reporting :)
